//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduzeniethFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnsID { get; set; }
        public string Ans { get; set; }
        public int statuss { get; set; }
        public int Quiz_id { get; set; }
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public int studentID { get; set; }
        public string studentName { get; set; }
        public int QuesID { get; set; }
        public string Question { get; set; }
    }
}
