//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduzeniethFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public string Grade1 { get; set; }
        public Nullable<System.DateTime> GradeDate { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public string Course_Name { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string Teacher_Name { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentName { get; set; }
    }
}
