//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduzeniethFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuesID { get; set; }
        public int CourseID { get; set; }
        public string Question1 { get; set; }
        public string Ans_A { get; set; }
        public string Ans_B { get; set; }
        public string Ans_C { get; set; }
        public string Ans_D { get; set; }
        public string Correct_Ans { get; set; }
        public int Quiz_id { get; set; }
    }
}
