//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduzeniethFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string father_name { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public string MaritalStatus { get; set; }
        public string MobileNumber { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string EducationalField { get; set; }
        public string NID_PassportNo { get; set; }
        public int Status { get; set; }
    }
}
